config/routes.rb
Rails.application.routes.draw do

  resources :games do
    collection do
      post :draw
      post :skip
    end
  end

  root 'home#index'

end

app/models/card.rb
class Card

  attr_reader :value, :type

  FACE_CARDS = [ 'K', 'Q', 'J' ]
  ACE_CARD = 'A'
  TYPES = {
    clubs: 1,
    diamonds: 2,
    hearts: 3,
    spades: 4
  }

  # TODO
  # Use a config object
  POINTS = {
    face_card: 10,
    ace_card: 11
  }

  def initialize(value, type)
    @value = value
    @type = TYPES[type.to_sym]
  end

  def face_card?
    FACE_CARDS.include?(@value)
  end

  def ace_card?
    @value === ACE_CARD
  end

  def points
    return POINTS[:face_card] if face_card?
    return POINTS[:ace_card] if ace_card?

    # If normal card
    return @value
  end
end

app/models/dealer.rb
class Dealer < Player

end

app/models/game.rb
class Game < ActiveRecord::Base

  MAX_POINTS = 21

  enum status: [ :started, :finished, :aborted ]

  # Associations
  has_many :game_players
  has_many :players, through: :game_players
  has_many :steps, through: :game_players
end

app/models/game_player.rb
class GamePlayer < ActiveRecord::Base

  enum status: [ :skipped, :busted ]

  DEALER_SKIP_LIMIT = 16

  # Associations
  has_many   :steps, class_name: GamePlayerStep
  belongs_to :game
  belongs_to :player

  # Validations
  validates :game, presence: true
  validates :player, presence: true
  
  def has_been_busted?
    points > Game::MAX_POINTS
  end

  def points
    steps.sum(:points)
  end

  def won?
    return false if busted?

    points === Game::MAX_POINTS ||
    opponent.busted? ||
    has_more_points? ||
    nil
  end

  def has_more_points?
    skipped? && opponent.skipped? && self.points >= opponent.points
  end

  # TODO
  # Support multi players
  # For now it will be only 1
  def opponent
    GamePlayer.where.not(player: self.player)
              .where(game: game)
              .first
  end

  def dealer?
    player.is_a? Dealer
  end

  def has_dealer_reached_skip_limit?
    dealer? && points > DEALER_SKIP_LIMIT
  end

  def normal_player?
    player.is_a? NormalPlayer
  end
end

app/models/game_player_step.rb
class GamePlayerStep < ActiveRecord::Base

  # Associations
  belongs_to :game_player

  # Validations
  validates :card_type, presence: true
  validates :card_value, presence: true
  validates :points, presence: true

  def card=(card)
    @card = card
    self.card_value = card.try(:value)
    self.card_type = card.try(:type)
  end

  def card
    @card ||= Card.new(card_value, card_type)
  end

  before_validation :set_points

  private
  def set_points
    self.points = card.points if card && new_record?
  end
end

app/models/normal_player.rb
class NormalPlayer < Player

end

app/models/player.rb
class Player < ActiveRecord::Base

  # Associations
  has_many :game_players
  has_many :games, through: :game_players
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/games_controller.rb
class GamesController < ApplicationController

  before_action :game, only: :show

  def index
    @games = Game.order(id: :asc)
                 .includes(game_players: [ :player ])
  end

  def show

  end

  def create
    player = NormalPlayer.first
    dealer = Dealer.first

    outcome = StartGame.call(dealer, player)
    result = outcome.result
    session[:game_id] = result.id

    render json: result
  end

  def draw
    DrawCard.call(game_player, draw_params)

    render json: {
      success: true,
      status: game_player.status,
      won: game_player.won?
    }
  end

  def skip
    if current_player.is_a?(NormalPlayer) && !game_player.busted?
        game_player.skipped!
        json = { success: true }
    else
      json = { success: false }
    end

    render json: json
  end

  private
  def current_player
    @current_player ||= params[:type].classify.constantize.first
  end

  def draw_params
    params.permit(cards: [ :type, :value ])
  end

  def game_player
    current_game.game_players.find_by!(player_id: current_player)
  end

  def game
    @game ||= Game.find(params[:id])
  end

  def current_game
    Game.find(session[:game_id])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/game_helper.rb
module GameHelper

  def game_winner(players)
    players.each do |player|
       yield(player) and return if player.won?
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/games/index.html.erb
<h3>Statistics</h3>
<a href="<%= root_url %>" class="btn btn-lg btn-primary">Deal Again</a>

<table class="table">
  <thead>
    <tr>
      <th>Games</th>
      <th>Players</th>
      <th>Result</th>
    </tr>
  </thead>
  <tbody>
    <% @games.each_with_index do |game, index| %>
      <tr>
        <td><h5>Game <%= index %></h5></td>
        <td>
        <% game.game_players.each do |game_player| %>
          <p><%= game_player.player.name %>: <%= game_player.points %></p>
        <% end %>
        </td>
        <td>
          <% game_winner(game.game_players) do |winner| %>
            <h3><%= winner.player.name %> / <%= winner.points %></h3>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<table>

app/views/home/index.html.erb
<div class='starter-template'>
  <h1>StrikerJack</h1>
  <p class="lead">Play BlackJack all you want..</p>
</div>

<%= react_component('sj.ui.Game') %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Strikerjack</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <style>
    body {
      padding-top: 50px;
    }
    .starter-template {
      padding: 40px 15px;
      text-align: center;
    }
  </style>
</head>
<body>


  <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">StrikerJack</a>
        </div>
        <ul class="nav navbar-nav">
          <li><%= link_to 'Statistics', games_path %></li>
        </ul>
    </nav>

    <div class="container">
      <%= yield %>
    </div>
</body>
</html>